### ISSUE TITLE
Añadir colaborador

### ISSUE THREAD

**Issue by patrickscln** [patrickscln/hello#2]
Añadir como colaborador del repositorio a mi compañero de equipo.

**Comment by vcuspinera** [comment]
Hola @joregc, me parece que aquí falta una colaboración, favor de revisar la [actividad 06](https://github.com/vcuspinera/UDG_MCD_Project_Dev_II/blob/main/actividades/06_GitHub_practice.md).

**Comment by joregc** [comment]
!Colaboración hecha, @vcuspinera!

Saludos.

**Comment by vcuspinera** [comment]
Gracias @joregc, super buena la imagen compartida!
